let count = 0;
count = 30;
let newCount = 0;
const daysInWeek = 7;
let tomatoCount;
let tomatocount;
let $tomato$Count;
let _tomato_Count;
let tomato7Count;
let トマトカウント;
let tomato_count;
let Tomato_count;

let additionResult = 2 + 5;
let result = 5;
result = result + 1;
result += 1;
console.log(++result);
result;
++result;
let number = 10;
number = -4;
number = 32.42;
let string = 'Hello';
number = 'something';
const userName = `Yoshipi`;
string = 'Hello ' + userName + '!';
string = `Hello ${userName}!`
string = ' " ` ` " ';
string = ` \\ `;
string = 'Hello\nYoshipi';
string = `Hello Yoshipi`;

const userInput = '10.9';
let calcResult;
calcResult = Number(userInput) + 10;
calcResult = parseInt(userInput) + 10;
calcResult = parseFloat(userInput) + 10;
const tenNumber = 10;
calcResult = '10' + tenNumber.toString();
console.log(calcResult);